### ISSUE TITLE
How should we use YAML configuration?

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#35]
With Spring Boot arrived in all services, we can now think about how we should use and structure the YAML-based configuration files. There are several question arising:
1. What namespace should we use for OSIAM's configuration properties? I'm in favor for `org.osiam.[service name].[property]`, i.e.
   
   ``` yaml
   org.osiam.auth-server:
     resource-server-home: http://localhost:8080/osiam-resource-server
     ldap.enabled: false
   ```
2. Should we wrap Spring configuration properties, i.e.
   
   ``` yaml
   org.osiam.spring.session-timeout: 240
   ```
   
   or just use the ones from Spring and let ops define additional ones if they need them?
3. Do we plan for a smooth transition of `.properties` files to YAML files, supporting both for some time (this might have an impact on 1. and 2.)?

What do you think? Any other questions on your minds?
